Return-Path: <netdev-owner@vger.kernel.org>
X-Original-To: lists+netdev@lfdr.de
Delivered-To: lists+netdev@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 7A00915FB51
	for <lists+netdev@lfdr.de>; Sat, 15 Feb 2020 01:08:38 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1727572AbgBOAIf (ORCPT <rfc822;lists+netdev@lfdr.de>);
        Fri, 14 Feb 2020 19:08:35 -0500
Received: from mail-qt1-f194.google.com ([209.85.160.194]:44266 "EHLO
        mail-qt1-f194.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1725946AbgBOAIf (ORCPT
        <rfc822;netdev@vger.kernel.org>); Fri, 14 Feb 2020 19:08:35 -0500
Received: by mail-qt1-f194.google.com with SMTP id k7so8159196qth.11
        for <netdev@vger.kernel.org>; Fri, 14 Feb 2020 16:08:34 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=ziepe.ca; s=google;
        h=date:from:to:cc:subject:message-id:references:mime-version
         :content-disposition:in-reply-to:user-agent;
        bh=b17aKGGo37hlriIldcmoz+zA0kaOJNJHOAY7BkBHEEk=;
        b=H/E8XY97zCl0Ib25evOj21LSEiM8N5LSI10j8qvatp+MzEW6YOGUFB9JUTPAKhcIvM
         W/RbP59wGMQnZ1Dww5jFb77KfhEuFo1i0igK9qeK3S5PFBnia2Tq+8lao2771TouepQA
         gIR9Dpxm5aPshfKWd9eFFMBMIOmiSjwoQJ+ppvFwHRe6Z7O8MY6yoT4qiKD6lQp5qNM0
         y2ut8xvgWYj8rjobujQdcBZ6y+OE/8K2W8Ijd1LvMz7whK9t8pm0dE2ZjpNUioobz+zq
         Ch9jYcn5M239LBLxiTqNicHIBKS2aMh9lJYtQlQTOFIgphTp6Ut9I413/hVIBVWTgqvq
         sY7Q==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:date:from:to:cc:subject:message-id:references
         :mime-version:content-disposition:in-reply-to:user-agent;
        bh=b17aKGGo37hlriIldcmoz+zA0kaOJNJHOAY7BkBHEEk=;
        b=WYm/ciafKfXSoSad370lF5Ri9584cm5RsIsYl3neD+QCPvjGxBMvbWRuv2Lu6/E6vD
         Uxbw937gBc39zDHchjJFxtTscmX+kMoPggHxa6X2MB3ELpmyPttzW2WhqH7a/iVWm4v2
         3hjnHzvL6A5YNxiiGM0T5Pkd2hDh4we7pS0Cdr1S6OngqccRKksSePf1lOzbha48qnyv
         TF/6nveTPfsGnJKMDs/chEp1dmerJXK/Pgqwc/DYXVYYWcpzqCSeqzJI/Ll176CC8yPu
         WiC3oXKA44GavLbp2++f6TOD9iTlsGcr23SZFeUfkjleiS09iuGGnrVJ/pl8pZkVcN9q
         otWw==
X-Gm-Message-State: APjAAAVhLuOwEKwV+c5p0UarHkOAXg8Q4pio04AXUNfcKQbQ/Tx/wWhg
        Dy4eXNo9EFP4cqeW3Qf9DY/Jiw==
X-Google-Smtp-Source: APXvYqwaX3Qx0JPPkN4W2i4VvkAqp+PbHoLHG0AyAgFRU7VWjYcrc1zecMEqMlyXjqs3YalcSS5+Cw==
X-Received: by 2002:aed:2266:: with SMTP id o35mr4713762qtc.392.1581725314463;
        Fri, 14 Feb 2020 16:08:34 -0800 (PST)
Received: from ziepe.ca (hlfxns017vw-142-68-57-212.dhcp-dynamic.fibreop.ns.bellaliant.net. [142.68.57.212])
        by smtp.gmail.com with ESMTPSA id b26sm4404148qkk.5.2020.02.14.16.08.33
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Fri, 14 Feb 2020 16:08:33 -0800 (PST)
Received: from jgg by mlx.ziepe.ca with local (Exim 4.90_1)
        (envelope-from <jgg@ziepe.ca>)
        id 1j2l0b-0003m7-Bl; Fri, 14 Feb 2020 20:08:33 -0400
Date:   Fri, 14 Feb 2020 20:08:33 -0400
From:   Jason Gunthorpe <jgg@ziepe.ca>
To:     Jeff Kirsher <jeffrey.t.kirsher@intel.com>
Cc:     davem@davemloft.net, gregkh@linuxfoundation.org,
        Dave Ertman <david.m.ertman@intel.com>, netdev@vger.kernel.org,
        linux-rdma@vger.kernel.org, nhorman@redhat.com,
        sassmann@redhat.com, parav@mellanox.com, galpress@amazon.com,
        selvin.xavier@broadcom.com, sriharsha.basavapatna@broadcom.com,
        benve@cisco.com, bharat@chelsio.com, xavier.huwei@huawei.com,
        yishaih@mellanox.com, leonro@mellanox.com, mkalderon@marvell.com,
        aditr@vmware.com, Kiran Patil <kiran.patil@intel.com>,
        Andrew Bowers <andrewx.bowers@intel.com>
Subject: Re: [RFC PATCH v4 01/25] virtual-bus: Implementation of Virtual Bus
Message-ID: <20200215000833.GA31668@ziepe.ca>
References: <20200212191424.1715577-1-jeffrey.t.kirsher@intel.com>
 <20200212191424.1715577-2-jeffrey.t.kirsher@intel.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <20200212191424.1715577-2-jeffrey.t.kirsher@intel.com>
User-Agent: Mutt/1.9.4 (2018-02-28)
Sender: netdev-owner@vger.kernel.org
Precedence: bulk
List-ID: <netdev.vger.kernel.org>
X-Mailing-List: netdev@vger.kernel.org

On Wed, Feb 12, 2020 at 11:14:00AM -0800, Jeff Kirsher wrote:
> From: Dave Ertman <david.m.ertman@intel.com>
> 
> This is the initial implementation of the Virtual Bus,
> virtbus_device and virtbus_driver.  The virtual bus is
> a software based bus intended to support registering
> virtbus_devices and virtbus_drivers and provide matching
> between them and probing of the registered drivers.
> 
> The bus will support probe/remove shutdown and
> suspend/resume callbacks.
> 
> Kconfig and Makefile alterations are included

Can you please include the various sysfs paths that are generated by
all of this for irdma in some commit message?

I'm particularly interested to see how all the parentage turned out
for the virtual device.

Is PM going to work? IIRC PM will require that the virtual bus device
goes through PM states in the right order relative to the PCI
device. This all turned out OK?

The concept certainly seems like what I imagined

I'm not totally sold on 'virtual bus' as a name for this 'multi
function pci device' thing, but you can work that out with Greg :)

Thanks,
Jason
